import * as vscode from 'vscode';

const COUNTRIES = [
	{ label: "W1", description: "W1" },	{ label: "AD", description: "Andorra" }, { label: "AE", description: "United Arab Emirates" },	
	{ label: "AF", description: "Afghanistan" }, { label: "AG", description: "Antigua and Barbuda" }, { label: "AI", description: "Anguilla" },	
	{ label: "AL", description: "Albania" }, { label: "AM", description: "Armenia" }, { label: "AO", description: "Angola" }, { label: "AQ", description: "Antarctica" },
	{ label: "AR", description: "Argentina" }, { label: "AS", description: "American Samoa" }, { label: "AT", description: "Austria" },	
	{ label: "AU", description: "Australia" }, { label: "AW", description: "Aruba" }, { label: "AX", description: "Åland Islands" },	
	{ label: "AZ", description: "Azerbaijan" },	{ label: "BA", description: "Bosnia and Herzegovina" },	{ label: "BB", description: "Barbados" },	
	{ label: "BD", description: "Bangladesh" },	{ label: "BE", description: "Belgium" }, { label: "BF", description: "Burkina Faso" },
	{ label: "BG", description: "Bulgaria" }, { label: "BH", description: "Bahrain" }, { label: "BI", description: "Burundi" },	{ label: "BJ", description: "Benin" },	
	{ label: "BL", description: "Saint Barthélemy" }, { label: "BM", description: "Bermuda" }, { label: "BN", description: "Brunei Darussalam" },	
	{ label: "BO", description: "Bolivia" }, { label: "BQ", description: "Bonaire" }, { label: "BR", description: "Brazil" }, { label: "BS", description: "Bahamas" },	
	{ label: "BT", description: "Bhutan" },	{ label: "BV", description: "Bouvet Island" },	{ label: "BW", description: "Botswana" }, { label: "BY", description: "Belarus" },	
	{ label: "BZ", description: "Belize" },	{ label: "CA", description: "Canada" },	{ label: "CC", description: "Cocos (Keeling) Islands" },	
	{ label: "CF", description: "Central African Republic" }, { label: "CG", description: "Congo" }, { label: "CH", description: "Switzerland" }, { label: "CI", description: "Côte d'Ivoire" },	
	{ label: "CK", description: "Cook Islands" }, { label: "CL", description: "Chile" }, { label: "CM", description: "Cameroon" }, { label: "CN", description: "China" },	
	{ label: "CO", description: "Colombia" }, { label: "CR", description: "Costa Rica" }, { label: "CU", description: "Cuba" },	{ label: "CV", description: "Cape Verde" },	
	{ label: "CW", description: "Curaçao" }, { label: "CX", description: "Christmas Island" }, { label: "CY", description: "Cyprus" }, { label: "CZ", description: "Czech Republic" },	
	{ label: "DE", description: "Germany" }, { label: "DJ", description: "Djibouti" }, { label: "DK", description: "Denmark" },	{ label: "DM", description: "Dominica" },	
	{ label: "DO", description: "Dominican Republic" }, { label: "DZ", description: "Algeria" }, { label: "EC", description: "Ecuador" }, { label: "EE", description: "Estonia" },	
	{ label: "EG", description: "Egypt" }, { label: "EH", description: "Western Sahara" }, { label: "ER", description: "Eritrea" }, { label: "ES", description: "Spain" },	
	{ label: "ET", description: "Ethiopia" }, { label: "FI", description: "Finland" }, { label: "FJ", description: "Fiji" }, { label: "FK", description: "Falkland Islands (Malvinas)" },	
	{ label: "FM", description: "Micronesia" }, { label: "FO", description: "Faroe Islands" }, { label: "FR", description: "France" }, { label: "GA", description: "Gabon" },	
	{ label: "GB", description: "United Kingdom" },	{ label: "GD", description: "Grenada" }, { label: "GE", description: "Georgia" }, { label: "GF", description: "French Guiana" },	
	{ label: "GG", description: "Guernsey" }, { label: "GH", description: "Ghana" }, { label: "GI", description: "Gibraltar" },	{ label: "GL", description: "Greenland" },	
	{ label: "GM", description: "Gambia" },	{ label: "GN", description: "Guinea" },	{ label: "GP", description: "Guadeloupe" },	{ label: "GQ", description: "Equatorial Guinea" },	
	{ label: "GR", description: "Greece" },	{ label: "GS", description: "South Georgia and the South Sandwich Islands" }, { label: "GT", description: "Guatemala" },	
	{ label: "GU", description: "Guam" }, { label: "GW", description: "Guinea-Bissau" }, { label: "GY", description: "Guyana" }, { label: "HK", description: "Hong Kong" },	
	{ label: "HM", description: "Heard Island and McDonald Islands" }, { label: "HN", description: "Honduras" }, { label: "HR", description: "Croatia" }, { label: "HT", description: "Haiti" },	
	{ label: "HU", description: "Hungary" }, { label: "ID", description: "Indonesia" }, { label: "IE", description: "Ireland" }, { label: "IL", description: "Israel" },	
	{ label: "IM", description: "Isle of Man" }, { label: "IN", description: "India" },	{ label: "IO", description: "British Indian Ocean Territory" },	{ label: "IQ", description: "Iraq" },	
	{ label: "IR", description: "Iran" }, { label: "IS", description: "Iceland" }, { label: "IT", description: "Italy" }, { label: "JE", description: "Jersey" },
	{ label: "JM", description: "Jamaica" }, { label: "JO", description: "Jordan" }, { label: "JP", description: "Japan" },	{ label: "KE", description: "Kenya" },	
	{ label: "KG", description: "Kyrgyzstan" },	{ label: "KH", description: "Cambodia" }, { label: "KI", description: "Kiribati" },	{ label: "KM", description: "Comoros" },	
	{ label: "KN", description: "Saint Kitts and Nevis" }, { label: "KR", description: "South Korea" }, { label: "KW", description: "Kuwait" },	
	{ label: "KY", description: "Cayman Islands" },	{ label: "KZ", description: "Kazakhstan" },	{ label: "LA", description: "Lao People's Democratic Republic" },	
	{ label: "LB", description: "Lebanon" }, { label: "LC", description: "Saint Lucia" }, { label: "LI", description: "Liechtenstein" },	
	{ label: "LK", description: "Sri Lanka" }, { label: "LR", description: "Liberia" },	{ label: "LS", description: "Lesotho" }, { label: "LT", description: "Lithuania" },	
	{ label: "LU", description: "Luxembourg" },	{ label: "LV", description: "Latvia" },	{ label: "LY", description: "Libya" },	{ label: "MA", description: "Morocco" },	
	{ label: "MC", description: "Monaco" },	{ label: "MD", description: "Moldova" }, { label: "ME", description: "Montenegro" }, { label: "MF", description: "Saint Martin (French part)" },	
	{ label: "MG", description: "Madagascar" },	{ label: "MH", description: "Marshall Islands" }, { label: "MK", description: "Macedonia" }, { label: "ML", description: "Mali" },	
	{ label: "MM", description: "Myanmar" }, { label: "MN", description: "Mongolia" }, { label: "MO", description: "Macao" }, { label: "MP", description: "Northern Mariana Islands" },	
	{ label: "MQ", description: "Martinique" }, { label: "MR", description: "Mauritania" },	{ label: "MS", description: "Montserrat" },	{ label: "MT", description: "Malta" },	
	{ label: "MU", description: "Mauritius" }, { label: "MV", description: "Maldives" }, { label: "MW", description: "Malawi" }, { label: "MX", description: "Mexico" },	
	{ label: "MY", description: "Malaysia" }, { label: "MZ", description: "Mozambique" }, { label: "NA", description: "Namibia" }, { label: "NC", description: "New Caledonia" },	
	{ label: "NE", description: "Niger" }, { label: "NF", description: "Norfolk Island" }, { label: "NG", description: "Nigeria" }, { label: "NI", description: "Nicaragua" },	
	{ label: "NL", description: "Netherlands" }, { label: "NO", description: "Norway" }, { label: "NP", description: "Nepal" }, { label: "NR", description: "Nauru" },	
	{ label: "NU", description: "Niue" }, { label: "NZ", description: "New Zealand" }, { label: "OM", description: "Oman" }, { label: "PA", description: "Panama" },	
	{ label: "PE", description: "Peru" }, { label: "PF", description: "French Polynesia" },	{ label: "PG", description: "Papua New Guinea" }, { label: "PH", description: "Philippines" },	
	{ label: "PK", description: "Pakistan" }, { label: "PL", description: "Poland" }, { label: "PM", description: "Saint Pierre and Miquelon" },	
	{ label: "PN", description: "Pitcairn" }, { label: "PR", description: "Puerto Rico" }, { label: "PS", description: "Palestine" }, { label: "PT", description: "Portugal" },	
	{ label: "PW", description: "Palau" }, { label: "PY", description: "Paraguay" }, { label: "QA", description: "Qatar" }, { label: "RE", description: "Réunion" },	
	{ label: "RO", description: "Romania" }, { label: "RS", description: "Serbia" }, { label: "RU", description: "Russian Federation" }, { label: "RW", description: "Rwanda" },	
	{ label: "SA", description: "Saudi Arabia" }, { label: "SB", description: "Solomon Islands" }, { label: "SC", description: "Seychelles" }, { label: "SD", description: "Sudan" },	
	{ label: "SE", description: "Sweden" }, { label: "SG", description: "Singapore" }, { label: "SH", description: "Saint Helena" }, { label: "SI", description: "Slovenia" },	
	{ label: "SJ", description: "Svalbard and Jan Mayen" }, { label: "SK", description: "Slovakia" }, { label: "SL", description: "Sierra Leone" }, { label: "SM", description: "San Marino" },	
	{ label: "SN", description: "Senegal" }, { label: "SO", description: "Somalia" }, { label: "SR", description: "Suriname" }, { label: "SS", description: "South Sudan" },	
	{ label: "ST", description: "Sao Tome and Principe" }, { label: "SV", description: "El Salvador" }, { label: "SX", description: "Sint Maarten" }, { label: "SY", description: "Syrian Arab Republic" },	
	{ label: "SZ", description: "Swaziland" }, { label: "TC", description: "Turks and Caicos Islands" }, { label: "TD", description: "Chad" }, { label: "TF", description: "French Southern Territories" },	
	{ label: "TG", description: "Togo" }, { label: "TH", description: "Thailand" }, { label: "TJ", description: "Tajikistan" }, { label: "TK", description: "Tokelau" },	
	{ label: "TL", description: "Timor-Leste" }, { label: "TM", description: "Turkmenistan" }, { label: "TN", description: "Tunisia" },	{ label: "TO", description: "Tonga" },	
	{ label: "TR", description: "Turkey" },  { label: "TT", description: "Trinidad and Tobago" }, { label: "TV", description: "Tuvalu" }, { label: "TW", description: "Taiwan" },	
	{ label: "TZ", description: "Tanzania" }, { label: "UA", description: "Ukraine" }, { label: "UG", description: "Uganda" },	{ label: "UM", description: "United States Minor Outlying Islands" },	
	{ label: "US", description: "United States" }, { label: "UY", description: "Uruguay" }, { label: "UZ", description: "Uzbekistan" }, { label: "VA", description: "Holy See (Vatican City State)" },	
	{ label: "VC", description: "Saint Vincent and the Grenadines" }, { label: "VE", description: "Venezuela" }, { label: "VG", description: "Virgin Islands, British" },
	{ label: "VI", description: "Virgin Islands, U.S." }, { label: "VN", description: "Vietnam" },	{ label: "VU", description: "Vanuatu" }, { label: "WF", description: "Wallis and Futuna" },	
	{ label: "WS", description: "Samoa" }, { label: "YE", description: "Yemen" }, { label: "YT", description: "Mayotte" }, { label: "ZA", description: "South Africa" },	
	{ label: "ZM", description: "Zambia" }, { label: "ZW", description: "Zimbabwe"}
];

export async function selectCountry(): Promise<{ label: string; description: string; } | undefined> {
	const countryCode = await vscode.window.showQuickPick(COUNTRIES, {
		placeHolder: 'Select a country'
	});

	return countryCode;
}
